version: "3"

services:
  node-ts:
    #image: node-ts
    build: . 
    restart: on-failure
    container_name: node-ts-container
    environment:
      MONGO_URI: mongodb://mongo_db:27017/?authSource=admin
    ports:
      - "8000:8000"
    links:
      - mongodb

  mongodb:
    image: mongo
    restart: on-failure
    container_name: mongo_db
    environment:
    - PUID=1000
    - PGID=1000
    ports:
      - "27017:27017"